project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
    - text : Hands-on Exercises
      menu : 
        - text: Hands-on Exercise 1 - Geospatial Data Wrangling with R
          href: Hands-on_Ex1/Hands-on_Ex1.1.qmd
        - text: Hands-on Exercise 1 - Choropleth Mapping with R
          href: Hands-on_Ex1/Hands-on_Ex1.2.qmd
        - text: Hands-on Exercise 2 - Spatial Weights and Applications
          href: Hands-on_Ex2/Hands-on_Ex2.1.qmd
        - text: Hands-on Exercise 2 - Global Measures of Spatial Autocorrelation
          href: Hands-on_Ex2/Hands-on_Ex2.2.qmd
        - text: Hands-on Exercise 2 - Local Measures of Spatial Autocorrelation
          href: Hands-on_Ex2/Hands-on_Ex2.3.qmd
        - text: Hands-on Exercise 3 - Processing and Visualising Flow Data
          href: Hands-on_Ex3/Hands-on_Ex3.qmd
    - text : In-Class Exercises
      menu : 
        - text: In-Class Exercise 2
          href: In-Class_Ex2/In-Class_Ex2.html
        - text: In-Class Exercise 3
          href: In-class_Ex3/In-Class_Ex3.html
    - text : Take-Home Exercises
      menu : 
        - text: Take-Home Exercise 1
          href: Take-Home_Ex1/Take-Home_Ex1.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

